#!/bin/bash
#$ -V
#$ -cwd
#$ -N rot_8I41
#$ -j y
#$ -q MS,UI-GPU
#$ -pe smp 20
#$ -o $JOB_NAME.$JOB_ID.log
#$ -l h_rt=10000:00:00
#$ -S /bin/bash
#$ -l ngpus=1
echo "=== Rotamer job started: $(date) ==="
echo "PDB: /Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/8I41/8I41_input.pdb"

# -------------------------------
# Java / ForceFieldX memory setup
# -------------------------------
# Explicit heap for ALL FFX JVMs
export JAVA_OPTS="-Xms4G -Xmx48G"
export FFX_OPTS="-Djava.awt.headless=true"

# --------------------------------
# Step 1: Coarse minimization
# --------------------------------
/Dedicated/schnieders/maemmad/forcefieldx/bin/ffxc Minimize \
  -e 0.8 \
  /Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/8I41/8I41_input.pdb \
  -Dkey=/Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/8I41/8I41_input.properties

# --------------------------------
# Step 2: Scheduler (limit heap + threads)
/Dedicated/schnieders/maemmad/forcefieldx/bin/ffxc Scheduler \
  -p 16 \
  -m 32G \
  > scheduler_rotamer.log &

sleep 20

# --------------------------------
# Step 3: ManyBody (FIXED)
# --------------------------------
/Dedicated/schnieders/maemmad/forcefieldx/bin/ffxc ManyBody \
  -Dpj.nn=1 \
  -Dpj.nt=16 \
  -DnumCudaDevices=1 \
  /Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/8I41/8I41_input.pdb_2 \
  -Dkey=/Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/8I41/8I41_input.properties

echo "=== Rotamer job done: $(date) ==="
