#!/bin/bash
#$ -V                        # Inherit current environment
#$ -cwd                      # Start job in submission directory
#$ -N rot_7M2Z             # Job Name
#$ -j y                      # Combine stderr and stdout
#$ -q MS,UI-GPU              # Queue
#$ -pe smp 20                # Request 20 tasks/node
#$ -o $JOB_NAME.$JOB_ID.log  # Name of output file
#$ -l h_rt=10000:00:00        # Run Time
#$ -S /bin/bash              # Shell to use
#$ -l ngpus=1
"=== Rotamer job started: $(date) ==="
echo "PDB: /Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/7M2Z/7M2Z_input.pdb"
# Step 1: Coarse minimize
FFX_JAVA_FLAGS="-Xms4G -Xmx40G" /Dedicated/schnieders/maemmad/forcefieldx/bin/ffxc Minimize -e 0.8 /Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/7M2Z/7M2Z_input.pdb -Dkey=/Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/7M2Z/7M2Z_input.properties
# Step 2: Rotamer optimization
FFX_JAVA_FLAGS="-Xms4G -Xmx40G" /Dedicated/schnieders/maemmad/forcefieldx/bin/ffxc Scheduler -p 20 -m 22G > scheduler_rotamer.log & sleep 30s
FFX_JAVA_FLAGS="-Xms4G -Xmx40G" /Dedicated/schnieders/maemmad/forcefieldx/bin/ffxc ManyBody -Dpj.nn=1 -Dpj.nt=20 -DnumCudaDevices=1 /Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/7M2Z/7M2Z_input.pdb_2 -Dkey=/Dedicated/schnieders/maemmad/pKa_GNN/ffx_pipeline/data/fixed_pdbs/7M2Z/7M2Z_input.properties
echo "=== Rotamer job done: $(date) ==="
